### ISSUE TITLE
Cannot connect to local registry

### ISSUE THREAD

**Issue by harche** [harche/stackup#1]
While trying to push the list manifest to local repository getting following error,

```
harshal@harshal-ThinkPad-T420:~/go/src/github.com/harche/stackup$ ./stackup --docker-cfg '/home/harshal/.docker/' /home/harshal/listm.yml
YAML File path - /home/harshal/go/src/github.com/runcom/skopeo/listm.yml
Getting the digests of the image names...
localhost:5000/hello-world : sha256:24f9fb9e8e6866a14015d8c01e7302b0d3b07eb8932d1ff9524523b50ee66892
localhost:5000/hello-world : sha256:24f9fb9e8e6866a14015d8c01e7302b0d3b07eb8932d1ff9524523b50ee66892
Manifest url : - https://localhost:5000/v2/localhost:5000/myimage/manifests/latest
panic: Get https://localhost:5000/v2/: tls: oversized record received with length 20527

goroutine 1 [running]:
github.com/harche/stackup/docker.PutData(0xc820194210, 0x7ffdc56a407d, 0x37)
    /home/harshal/go/src/github.com/harche/stackup/docker/inspect.go:252 +0x1f8a
main.inspect(0xc820194210)
    /home/harshal/go/src/github.com/harche/stackup/inspect.go:28 +0x183
main.glob.func1(0xc820194210)
    /home/harshal/go/src/github.com/harche/stackup/main.go:17 +0x21
github.com/harche/stackup/vendor/github.com/codegangsta/cli.(*App).Run(0xc820184600, 0xc820072100, 0x4, 0x4, 0x0, 0x0)
    /home/harshal/go/src/github.com/harche/stackup/vendor/github.com/codegangsta/cli/app.go:132 +0xad8
main.main()
    /home/harshal/go/src/github.com/harche/stackup/main.go:53 +0x53f

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 20 [syscall]:
os/signal.loop()
    /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
    /usr/local/go/src/os/signal/signal_unix.go:28 +0x37
```

This was the input YAML. Image localhost:5000/hello-world already exists in the local repository.

```
--- 
image: localhost:5000/myimage
manifests: 
  - 
    image: localhost:5000/hello-world
    platform: 
      architecture: ppc64
      os: Linux
      variant: ppc64le
  - 
    image: localhost:5000/hello-world
    platform: 
      architecture: x86_64
      features: 
        - sse
      os: Linux
```
