### ISSUE TITLE
Bad request while pushing list manifest to docker hub

### ISSUE THREAD

**Issue by harche** [harche/stackup#2]
While trying to push the list manifest to docker hub getting following error,

```
harshal@harshal-ThinkPad-T420:~/go/src/github.com/harche/stackup$ ./stackup --docker-cfg '/home/harshal/.docker/' /home/harshal/listm.yml.remote 
YAML File path - /home/harshal/go/src/github.com/runcom/skopeo/listm.yml.remote
Getting the digests of the image names...
docker.io/fedora:rawhide : sha256:b9cf7bff17d0b3b987db167832adfe21f2d84f78bb1d9d5e764de123aab76476
docker.io/ubuntu:latest : sha256:4e85ebe01d056b43955250bbac22bdb8734271122e3c78d21e55ee235fc6802d
Manifest url : - https://registry-1.docker.io/v2/pharshal/myimagasssdfdfdsfdsfdsfessiiddd/manifests/latest
400 Bad Request
```

The response body contains, 

```
TAG_INVALID  manifest tag did not match URI
```

How ever there is no apparent error in that way tag is handled during manifest list upload.

YAML used for input,

```
--- 
image: pharshal/myimagasssdfdfdsfdsfdsfessiiddd
manifests: 
  - 
    image: docker.io/fedora:rawhide
    platform: 
      architecture: ppc64
      os: Linux
      variant: ppc64le
  - 
    image: docker.io/ubuntu:latest
    platform: 
      architecture: x86_64
      features: 
        - sse
      os: Linux
```
